### ISSUE TITLE
Channel Stats not printing on Serial Monitor

### ISSUE THREAD

**Issue by HeathenHacks** [witnessmenow/arduino-youtube-api#10]
I'm not sure if I am the only one having this.

I'm using the ESP8266 -> ChannelStatistics code example. Followed all the instructions. 

Connecting Wifi: 
15:49:46.362 -> ..........
15:49:52.115 -> WiFi connected
15:49:52.115 -> IP address: 
15:49:52.115 ->

Shows up fine, but my channel's stats does not show up, no matter how long I wait.

**Comment by witnessmenow** [comment]
What version of esp8266 core are you using?

If it's 2.5 , you probably need to add client.setInsecure(); to your setup
method

**Comment by hea7henh4cks** [comment]
Oh, thanks for the fast response.

I'm using version 2.4.2

HeathenHacks here.

**Comment by witnessmenow** [comment]
I think 2.4.2 should be fine.

Are you sure the API key is correct?

**Comment by hea7henh4cks** [comment]
Yes. It's working fine on the googleapis URL checker on my browser.

**Comment by hea7henh4cks** [comment]
Here's a screenshot.

![desktop screenshot 2019 01 24 - 17 28 13 32](https://user-images.githubusercontent.com/5551915/51668766-e2934500-1ffd-11e9-9d84-20f988bc2bd5.png)

**Comment by witnessmenow** [comment]
Do you get a valid IP address in the serial monitor?

**Comment by hea7henh4cks** [comment]
Yes. I'm also using a generic D1 Mini as an MCU, I used the WEMOS D1 Mini board and ArduinoJson version 5.13.4 library, if that could help.

**Comment by hea7henh4cks** [comment]
Fixed it. Sorry for the hassle, sir. 

My bad.

**Comment by JaZzMaN251** [comment]
> Fixed it. Sorry for the hassle, sir.
> 
> My bad.

How did you fix it? I'm having the same issue.

**Comment by Maximuskembo** [comment]
How did you fix this? I have the same problem. Only wifi connection and ip adress show up in serial monitor. Please help :)

**Comment by JaZzMaN251** [comment]
I ended up creating a new project on Google API and creating a new YouTube API key. After a couple minutes, the key was activated and it showed the stats. 
(just creating a new API key in the existing project didn’t work, I really needed to create a new project)

**Comment by Maximuskembo** [comment]
Thanks for you answer.
I tried to create a new project in Google API and inserted the new API key (with no restrictions). 
I have waited for 30 minutes now and no difference from the serial monitor. See screenshot.
![serialmonitor1](https://user-images.githubusercontent.com/29666215/52176952-a3fa4900-27ba-11e9-9c05-a643b10fb52c.png)
Do you know if there is any way of monitoring if the ESP8266 sends a request to google? It looks like there is no activety?

**Comment by JaZzMaN251** [comment]
You can add a couple messages like this in between the code to print to the monitor:

Serial.println("start stat request");

**Comment by Maximuskembo** [comment]
Ok, I will try to do that.
I'l let you know how it goes :)
Thanks

**Comment by witnessmenow** [comment]
Are you using ESP8266 2.5 beta? if so you will need to add this line to
your setup method:

client.setInsecure();

**Comment by Maximuskembo** [comment]
Hi

Thank you so much, adding that line to the setup right here: 
![fix](https://user-images.githubusercontent.com/29666215/52194642-fa1bca80-2854-11e9-96ba-706680df91ba.png)
 Fixed the problem. I am using the Wemos D1 mini pro board.
I am making a youtube video about making this live counter so I was wondering if its ok to include this thread in the video?
Thanks again for helping out!!

regards 
Willys Garage Norway
