### ISSUE TITLE
Channel stats not showing up in serial monitor

### ISSUE THREAD

**Issue by Maximuskembo** [witnessmenow/arduino-youtube-api#11]
Hi
I have a project using the Wemos R1 chip.
In serial monitor I only get the response that the chip is connected. Wifi connected and an local ip address (like 192.34........)

And no matter how long I wait, the youtube channel stats does not show up.
The API key is correct (checked and working ok on googleapi link)
The router i'm connecting thru is connected to the internet.
Have you heard about this problem and do you have a fix for me?

Thanks

**Comment by kuuriisuu** [comment]
I'm facing the same issue. 
Did you get this resolved, +Maximuskembo?

**Comment by witnessmenow** [comment]
If you are using ESP8266 library 2.5, add "client.setInsecure();" to your
setup

**Comment by kuuriisuu** [comment]
Exquisite! That did it for me. I'm now able to retrieve stats. Thanks!! :)

**Comment by witnessmenow** [comment]
Added to the example in #23
