### ISSUE TITLE
Error compiling, tells me to upgrade to version 6

### ISSUE THREAD

**Issue by MrWilliam932** [witnessmenow/arduino-youtube-api#15]
error: DynamicJsonBuffer is a class from ArduinoJson 5. Please see arduinojson.org/upgrade to learn how to upgrade your program to ArduinoJson version 6

  DynamicJsonBuffer jsonBuffer;

           ^

In member function 'bool YoutubeApi::getChannelStatistics(String)':

error: 'jsonBuffer' was not declared in this scope

  DynamicJsonBuffer jsonBuffer;

                    ^

error: 'ArduinoJson::JsonObject' has no member named 'success'

  if(root.success()) {

          ^

**Comment by witnessmenow** [comment]
Downgrade your Arduino JSON to version 5, this library doesn't currently
support v6

**Comment by witnessmenow** [comment]
Fixed in #23
