### ISSUE TITLE
Not working anymore?

### ISSUE THREAD

**Issue by necoinside** [witnessmenow/arduino-youtube-api#18]
Hi,
I'm trying with wemos d1 r1, I've api_key that works with link that written in ReadMe, also board connects wifi and able to ping google.
But nothing more, no return as json to the board.
Note: Already downgraded ArduinoJson to 5.x and also tried to downgrade esp8266 lib to 2.5.0 but with no result.
Note2: client.setInsecure(); line added to setup() place too and again with no result.

**Comment by rsuriano** [comment]
I think it might be a problem with the API itself. I had a project using this library and Youtube Statistics and it suddenly stopped working, same as you're describing. Could you come up with a fix these past few days?

Edit: It worked after I added that client.setInsecure(); line, I'm on an ESP8266.

**Comment by defwheezer** [comment]
I also had the same youtubeapi problem using a NodeMCU, but it worked after I added the following line in setup():

client.setInsecure();

**Comment by necoinside** [comment]
I rewrote the sketch including BearSSLClient, its requirements and also client.setInsecure(); than it has started to work.

**Comment by ssttaarr33** [comment]
Can you please share the sketch? I can't get it working

**Comment by necoinside** [comment]
I've cleanly modified the original sketch for you and uploaded here @ssttaarr33 
[ChannelStatisticsModified.zip](https://github.com/witnessmenow/arduino-youtube-api/files/4433744/ChannelStatisticsModified.zip)
