### ISSUE TITLE
Does not connect to wifi

### ISSUE THREAD

**Issue by SensorsIot** [witnessmenow/arduino-youtube-api#2]
Little change was necessary in the example file: 

  WiFi.begin(ssid, password);
  while (WiFi.status() != WL_CONNECTED) {

**Comment by witnessmenow** [comment]
Hey Andreas,

I actually made that change after your reply on YouTube but I guess I haven't pushed it up to github yet!

I will do it when I home later. Thanks!

**Comment by witnessmenow** [comment]
Updated example with @SensorsIot suggestion
