### ISSUE TITLE
not able to parse correctly

### ISSUE THREAD

**Issue by elan22** [witnessmenow/arduino-youtube-api#24]
Hi,
Not sure if this is just me seeing this but I could not get the getChannelStatistics to give back results and after digging ended finding out that for some reason the response string being return had some chars (1f3) right at the beginning and that seemed to mess with the parser.
doing this:
String response = sendGetToYoutube(command);       //recieve reply from youtube
response.remove(0,3);

seemed to solve the issue.

**Comment by witnessmenow** [comment]
This was fixed in #23 which was released yesterday.

You would have to update your YouTube library (to v2.0) and Arduino JSON
library (to v6.x)

V2 of this library should be much more memory efficient and probably faster

**Comment by elan22** [comment]
aah, I was struggling with this for while now and didn't even check for updates.
Thanks for your work
