### ISSUE TITLE
Connection failed

### ISSUE THREAD

**Issue by glsf91** [witnessmenow/arduino-youtube-api#27]
My counter (Nodemcu esp8266) was working for years. Suddenly it stopped working.
I saw the closed issues about this.

I updated to your newest version and also ArduinoJson. I use ESP 8266 version 2.4.2.

But now I get:
/youtube/v3/channels?part=statistics&id= removed
Connection failed
Unexpected HTTP Status Code: 0
/youtube/v3/channels?part=statistics&id= removed
Tossing an unexpected character: 1
Tossing an unexpected character: d
Tossing an unexpected character: 1
Tossing an unexpected character: 

Tossing an unexpected character: 

Unexpected HTTP Status Code: 403
Closing client
/youtube/v3/channels?part=statistics&id= removed
Tossing an unexpected character: 1
Tossing an unexpected character: d
Tossing an unexpected character: 1
Tossing an unexpected character: 

and so on.
I also get this with the example included.

What can be the problem?

**Comment by witnessmenow** [comment]
403 is usually an authentication issue. I would double check your API token
is still valid.

**Comment by glsf91** [comment]
I'am sorry. Very stupid.
When trying in a browser I get:
The request cannot be completed because you have exceeded your <a href=\"/youtube/v3/getting-started#quota\">quota

Probably because of the lot of failures.
Now to find out how much the quota is and when it is reset. Looks like it is a 1000 requests per day, reset every day.
