### ISSUE TITLE
can u suggest me a way so that everytime someone subscribes a buzzer buzzes for 10 seconds .thanks

### ISSUE THREAD

**Issue by MagmaBeast** [witnessmenow/arduino-youtube-api#44]

**Comment by MagmaBeast** [comment]
here is the code os far doesnt work :(
`
/*******************************************************************
Read YouTube Channel statistics from the YouTube API on
an ESP8266 and print them to the serial monitor

Parts:
D1 Mini ESP8266 (or any ESP8266) * - http://s.click.aliexpress.com/e/uzFUnIe
* = Affilate

If you find what I do useful and would like to support me,
please consider becoming a sponsor on Github
https://github.com/sponsors/witnessmenow/

Written by Brian Lough
YouTube: https://www.youtube.com/brianlough
Tindie: https://www.tindie.com/stores/brianlough/
Twitter: https://twitter.com/witnessmenow
*******************************************************************/
#include <Servo.h>
Servo servo;

// ---------------------------
// Standard Libraries
// ----------------------------

#include <ESP8266WiFi.h>
#include <WiFiClientSecure.h>

// ----------------------------
// Additional Libraries - each one of these will need to be installed.
// ----------------------------

#include <YoutubeApi.h>
// Library for connecting to the Youtube API

// Search for "youtube" in the Arduino Library Manager
// https://github.com/witnessmenow/arduino-youtube-api

#include <ArduinoJson.h>
// Library used for parsing Json from the API responses

// Search for "Arduino Json" in the Arduino Library manager
// https://github.com/bblanchon/ArduinoJson

//------- Replace the following! ------
char ssid[] = "ghgj"; // your network SSID (name)
char password[] = "ghgj"; // your network key
#define API_KEY "" // your google apps API Token
#define CHANNEL_ID "UC34fGHsu-MXw3-S9FxaZqEw" // makes up the url of channel
//------- ---------------------- ------

WiFiClientSecure client;
YoutubeApi api(API_KEY, client);

unsigned long timeBetweenRequests = 0;
unsigned long nextRunTime;

long subs = 0;

void setup() {

servo.attach(D4);
servo.write(90);
Serial.begin(115200);
digitalWrite(D2,LOW);
// Set WiFi to station mode and disconnect from an AP if it was Previously
// connected
WiFi.mode(WIFI_STA);
WiFi.disconnect();
delay(0);

// Attempt to connect to Wifi network:
Serial.print("Connecting Wifi: ");
Serial.println(ssid);
WiFi.begin(ssid, password);
while (WiFi.status() != WL_CONNECTED) {
Serial.print(".");
delay(0);
}
Serial.println("");
Serial.println("WiFi connected");
Serial.println("IP address: ");
IPAddress ip = WiFi.localIP();
Serial.println(ip);

// Required if you are using ESP8266 V2.5 or above
client.setInsecure();

// If you want to enable some extra debugging
api._debug = false;
}

void loop() {

if (millis() > nextRunTime) {
if(api.getChannelStatistics(CHANNEL_ID))
{

  Serial.print("Subscriber Count: ");
  Serial.println(api.channelStats.subscriberCount);
 subs = api.channelStats.subscriberCount +1 ;

}
nextRunTime = millis() + timeBetweenRequests;
}

if(subs == api.channelStats.subscriberCount + 1 ){
digitalWrite(D5,HIGH);
delay(10000);
digitalWrite(D5,LOW);
}

}`

**Comment by joeybab3** [comment]
As I mentioned here: https://github.com/witnessmenow/arduino-youtube-api/issues/43#issuecomment-837683501
Instead of comparing to subcount + 1, try just seeing if it is not equal to it. Writing high to a buzzer will not make any noise, I suggest you review some sample code for making tones on a buzzer.

**Comment by MagmaBeast** [comment]
i have tried the buzzer with a normal high function it works  can u help me with how i can get and check subscibers every 60 secs and compare  the new value to the old

`
/*******************************************************************
    Read YouTube Channel statistics from the YouTube API on
    an ESP8266 and print them to the serial monitor
                                                                  
    Parts:
    D1 Mini ESP8266 (or any ESP8266) * - http://s.click.aliexpress.com/e/uzFUnIe
    * = Affilate
   
    If you find what I do useful and would like to support me,
    please consider becoming a sponsor on Github
    https://github.com/sponsors/witnessmenow/

    Written by Brian Lough
    YouTube: https://www.youtube.com/brianlough
    Tindie: https://www.tindie.com/stores/brianlough/
    Twitter: https://twitter.com/witnessmenow
 *******************************************************************/
 #include <Servo.h>
Servo servo; 

// ---------------------------
// Standard Libraries
// ----------------------------

#include <ESP8266WiFi.h>
#include <WiFiClientSecure.h>

// ----------------------------
// Additional Libraries - each one of these will need to be installed.
// ----------------------------

#include <YoutubeApi.h>
// Library for connecting to the Youtube API

// Search for "youtube" in the Arduino Library Manager
// https://github.com/witnessmenow/arduino-youtube-api

#include <ArduinoJson.h>
// Library used for parsing Json from the API responses

// Search for "Arduino Json" in the Arduino Library manager
// https://github.com/bblanchon/ArduinoJson

//------- Replace the following! ------
char ssid[] = "";       // your network SSID (name)
char password[] = "";  // your network key
#define API_KEY ""  // your google apps API Token
#define CHANNEL_ID "UC34fGHsu-MXw3-S9FxaZqEw" // makes up the url of channel
//------- ---------------------- ------

WiFiClientSecure client;
YoutubeApi api(API_KEY, client);

unsigned long timeBetweenRequests = 0;
unsigned long nextRunTime;

long oldsubs = 0;
long newsubs = 0;
void setup() {
  
  servo.attach(D4);
servo.write(90);
  Serial.begin(115200);
digitalWrite(D2,LOW);
  // Set WiFi to station mode and disconnect from an AP if it was Previously
  // connected
  WiFi.mode(WIFI_STA);
  WiFi.disconnect();
  delay(0);

  // Attempt to connect to Wifi network:
  Serial.print("Connecting Wifi: ");
  Serial.println(ssid);
  WiFi.begin(ssid, password);
  while (WiFi.status() != WL_CONNECTED) {
    Serial.print(".");
    delay(0);
  }
  Serial.println("");
  Serial.println("WiFi connected");
  Serial.println("IP address: ");
  IPAddress ip = WiFi.localIP();
  Serial.println(ip);

  // Required if you are using ESP8266 V2.5 or above
  client.setInsecure();

  // If you want to enable some extra debugging
  api._debug = false;
}
 
void loop() {

 
    if(api.getChannelStatistics(CHANNEL_ID))
    {
     
      Serial.print("Subscriber Count: ");
      Serial.println(api.channelStats.subscriberCount);
      long oldsubs = api.channelStats.subscriberCount;
     delay(20000);
   
  }

  
    if(api.getChannelStatistics(CHANNEL_ID))
    {
     
      Serial.print("Subscriber Count: ");
      Serial.println(api.channelStats.subscriberCount);
      long newsubs = api.channelStats.subscriberCount;
    }
  if(newsubs >  oldsubs){
    digitalWrite(D5,HIGH);
    delay(5000);
    digitalWrite(D5,LOW);
    newsubs = oldsubs;
    }

else {if(api.getChannelStatistics(CHANNEL_ID))
    {
     
      Serial.print("Subscriber Count: ");
      Serial.println(api.channelStats.subscriberCount);
      long newsubs = api.channelStats.subscriberCount;}
}
}`

**Comment by MagmaBeast** [comment]
@witnessmenow @dmadison  sir can u help

**Comment by dmadison** [comment]
With due respect @MagmaBeast I don't work for you. If you don't know how to program there are many C++ tutorials to learn available for free online. Otherwise you can hire a programmer to do it for you. If your budget is low you may be able to find someone on Fiverr.
