### ISSUE TITLE
Connection failed

### ISSUE THREAD

**Issue by Fardenco** [witnessmenow/arduino-youtube-api#48]
I'm getting this error when trying to get the datas for my channel :

Connection failed
Unexpected HTTP Status Code: 0

My API credentials are ok, I tested https://www.googleapis.com/youtube/v3/channels?part=statistics&id=xxx&key=yyy in a browser and I get the expected json

**Comment by witnessmenow** [comment]
Adding `client.setInsecure();`to your setup will probably fix it

**Comment by Fardenco** [comment]
That solved the issue,. I just found out that I was not running the last version of the example code, which indeed includes this fix.
Thank you 👍
