### ISSUE TITLE
example code leads to an HTTP status 0

### ISSUE THREAD

**Issue by taewyth** [witnessmenow/arduino-youtube-api#49]
I wanted to try the code example to make sure everything worked, but it returns and HTTP status 0, so I added the ESP32Ping library to ping googleapis.com to see if at least it could be reached, and it apparently does, that's the only modification made to the example code (aside from the necessary ones)

Here's the serial monitor readings:
![youtube issue](https://user-images.githubusercontent.com/43884526/141612456-db61c5dc-5278-4c98-8c11-346fe4ed81ca.png)

I also tried with your channel ID (as provided on the readme file), the issue stays here.

for more details:
* YoutubeApi version: 2.0.0
* ArduinoJson version: 6.18.5
* [card used](https://joy-it.net/en/products/SBC-NodeMCU-ESP32)

**Comment by witnessmenow** [comment]
I think its a HTTPs verification thing. ESP32 changed the default behavior not too log ago 

Change this:

```
#ifdef ESP8266
// Required if you are using ESP8266 V2.5 or above
client.setInsecure();
#endif
```

to 

```
client.setInsecure();
```

And it should work.

**Comment by taewyth** [comment]
Yep, that was it. Thanks!
