### ISSUE TITLE
Limited Space Availible For JSON

### ISSUE THREAD

**Issue by montypx** [witnessmenow/arduino-youtube-api#7]
I don't quite know why but for some reason although I have allocated more than enough space for the 
Youtube API request i cannot seem to parse the JSON as the String just ends towards the end most likely
due to insufficent space I cannot seem to allocate more memory.
 
I'm using the snippet data from a channel. Is anyone else having this problem?

**Comment by witnessmenow** [comment]
This is handled completely differently now since #23, so please report back if you still have issues
